Repository tower-rs/tower-http, pull requests merged in 2021-11, with the labels that each got.

#160 Add examples for `ServeDir`
  tower-http/Cargo.toml
  tower-http/src/services/fs/serve_dir.rs
Labels: T-docs

#112 Add `Cors` for setting CORS headers
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
  tower-http/src/cors.rs
  tower-http/src/lib.rs
Labels: A-new-middleware

#156 Precompressed files
  test-files/only_gzipped.txt.gz
  test-files/precompressed.txt
  test-files/precompressed.txt.br
  test-files/precompressed.txt.gz
  test-files/precompressed.txt.zz
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
  tower-http/src/compression/future.rs
  tower-http/src/compression/mod.rs
  tower-http/src/compression/service.rs
  tower-http/src/compression_utils.rs
  tower-http/src/content_encoding.rs
  tower-http/src/decompression/future.rs
  tower-http/src/lib.rs
  tower-http/src/services/fs/mod.rs
  tower-http/src/services/fs/serve_dir.rs
  tower-http/src/services/fs/serve_file.rs
Labels: breaking change

#172 Add compression predicate API
  tower-http/CHANGELOG.md
  tower-http/src/compression/future.rs
  tower-http/src/compression/layer.rs
  tower-http/src/compression/mod.rs
  tower-http/src/compression/predicate.rs
  tower-http/src/compression/service.rs
  tower-http/src/compression_utils.rs
  tower-http/src/decompression/service.rs
Labels: C-enhancement, A-new-util

#150 Add `SetRequestId` and `PropagateRequestId` middleware
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
  tower-http/src/builder.rs
  tower-http/src/lib.rs
  tower-http/src/request_id.rs
Labels: A-new-middleware

#189 Make `GrpcErrorsAsFailures` more flexible
  examples/tonic-key-value-store/src/main.rs
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
  tower-http/src/classify/grpc_errors_as_failures.rs
  tower-http/src/classify/mod.rs
  tower-http/src/compression/layer.rs
  tower-http/src/trace/on_eos.rs
  tower-http/src/trace/on_response.rs
Labels: C-enhancement
