Repository tower-rs/tower-http, pull requests merged in 2022-02, with the labels that each got.

#217 Release 0.2.2
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
Labels: T-release

#223 Release 0.2.3
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
Labels: T-release

#219 Optimize CORS future
  tower-http/src/cors.rs
Labels: breaking change

#214 Add `CatchPanic`
  tower-http/CHANGELOG.md
  tower-http/Cargo.toml
  tower-http/src/builder.rs
  tower-http/src/catch_panic.rs
  tower-http/src/lib.rs
Labels: A-new-middleware
